# input vcf with variants to be genotyped
vcf: /net/eichler/vol27/projects/hprc/nobackups/analysis/merge/chm13_v1.1/HGSVC_HPRC_PangenieNRID-minus.vcf.gz 

# reference genome
reference: /net/eichler/vol26/eee_shared/assemblies/CHM13/T2T/v1.1/chm13_v1.1_plus38Y_masked.fasta
reference_shortRead: /net/eichler/vol26/eee_shared/assemblies/hg38/1kg/GRCh38_full_analysis_set_plus_decoy_hla.fa

# name of the output directory
frac_missing: 0.2

# kmer size
kmer_size: 31

genotypeRegion: True
region_shortRead: "chr11:1157953-1201138"

# input type for short-read genomes
shortReadGenome:
    CRAM:
        HG00731: /net/eichler/vol26/projects/1kg_high_coverage/nobackups/data/Illumina/cram/HG00731.final.cram
        HG00732: /net/eichler/vol26/projects/1kg_high_coverage/nobackups/data/Illumina/cram/HG00732.final.cram
        HG00733: /net/eichler/vol26/projects/1kg_high_coverage/nobackups/data/Illumina/cram/HG00733.final.cram
        NA12878: /net/eichler/vol26/projects/1kg_high_coverage/nobackups/data/Illumina/cram/NA12878.final.cram
        NA19238: /net/eichler/vol26/projects/1kg_high_coverage/nobackups/data/Illumina/cram/NA19238.final.cram
